# Generated by Django 2.2 on 2019-11-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_'),
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
    ]
